# Generated by Django 5.1.2 on 2024-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendee",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="attendee",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
