# Generated by Django 5.1.2 on 2024-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_rename_name_attendee_first_name_attendee_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="middle_initial",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="attendee",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="attendee",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
