# Generated by Django 5.1.2 on 2024-11-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_attendee_middle_initial_attendee_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="nickname",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
