# Generated by Django 5.1.2 on 2024-11-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_alter_attendee_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
